spring.application.name=tg-livechat-bridge

server.port=8080

app.cors.allowed-origins=*

# Telegram
telegram.bot-token=8617466901:AAGS3MCpBve1AMp04b1v9E9zfoCBymzGpcE
telegram.admin-chat-id=-1003732038316
telegram.webhook-secret=mySecret123_ChangeMe
telegram.link-ttl=6h